//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceReferenceTrabajadores {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trabajador", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Trabajador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private System.DateTime UltimoLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime UltimoLogin {
            get {
                return this.UltimoLoginField;
            }
            set {
                if ((this.UltimoLoginField.Equals(value) != true)) {
                    this.UltimoLoginField = value;
                    this.RaisePropertyChanged("UltimoLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap")]
    public interface WebServiceTrabajadoresSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponse HelloWorld(CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponse> HelloWorldAsync(CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarLogin", ReplyAction="*")]
        CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponse ValidarLogin(CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponse> ValidarLoginAsync(CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarLogin", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequestBody Body;
        
        public ValidarLoginRequest() {
        }
        
        public ValidarLoginRequest(CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidarLoginRequestBody() {
        }
        
        public ValidarLoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponseBody Body;
        
        public ValidarLoginResponse() {
        }
        
        public ValidarLoginResponse(CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceReferenceTrabajadores.Trabajador ValidarLoginResult;
        
        public ValidarLoginResponseBody() {
        }
        
        public ValidarLoginResponseBody(CapaGUI.ServiceReferenceTrabajadores.Trabajador ValidarLoginResult) {
            this.ValidarLoginResult = ValidarLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTrabajadoresSoapChannel : CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTrabajadoresSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap>, CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap {
        
        public WebServiceTrabajadoresSoapClient() {
        }
        
        public WebServiceTrabajadoresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTrabajadoresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTrabajadoresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTrabajadoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponse CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap.HelloWorld(CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest inValue = new CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest();
            inValue.Body = new CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequestBody();
            CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponse retVal = ((CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponse> CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap.HelloWorldAsync(CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceReferenceTrabajadores.HelloWorldResponse> HelloWorldAsync() {
            CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest inValue = new CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequest();
            inValue.Body = new CapaGUI.ServiceReferenceTrabajadores.HelloWorldRequestBody();
            return ((CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponse CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap.ValidarLogin(CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest request) {
            return base.Channel.ValidarLogin(request);
        }
        
        public CapaGUI.ServiceReferenceTrabajadores.Trabajador ValidarLogin(string email, string password) {
            CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest inValue = new CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest();
            inValue.Body = new CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponse retVal = ((CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap)(this)).ValidarLogin(inValue);
            return retVal.Body.ValidarLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponse> CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap.ValidarLoginAsync(CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest request) {
            return base.Channel.ValidarLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceReferenceTrabajadores.ValidarLoginResponse> ValidarLoginAsync(string email, string password) {
            CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest inValue = new CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequest();
            inValue.Body = new CapaGUI.ServiceReferenceTrabajadores.ValidarLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CapaGUI.ServiceReferenceTrabajadores.WebServiceTrabajadoresSoap)(this)).ValidarLoginAsync(inValue);
        }
    }
}
