//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceReferenceValeConsumo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValeConsumo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ValeConsumo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int IdTrabajadorField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTrabajador {
            get {
                return this.IdTrabajadorField;
            }
            set {
                if ((this.IdTrabajadorField.Equals(value) != true)) {
                    this.IdTrabajadorField = value;
                    this.RaisePropertyChanged("IdTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salida", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Salida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int IdValeConsumoField;
        
        private int IdProductoField;
        
        private int NumeroUnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdValeConsumo {
            get {
                return this.IdValeConsumoField;
            }
            set {
                if ((this.IdValeConsumoField.Equals(value) != true)) {
                    this.IdValeConsumoField = value;
                    this.RaisePropertyChanged("IdValeConsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumeroUnidades {
            get {
                return this.NumeroUnidadesField;
            }
            set {
                if ((this.NumeroUnidadesField.Equals(value) != true)) {
                    this.NumeroUnidadesField = value;
                    this.RaisePropertyChanged("NumeroUnidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceValeConsumo.WebServiceValeConsumoSoap")]
    public interface WebServiceValeConsumoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponse HelloWorld(CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponse> HelloWorldAsync(CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento valeConsumo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarConsumo", ReplyAction="*")]
        CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponse GenerarConsumo(CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarConsumo", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponse> GenerarConsumoAsync(CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarConsumoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarConsumo", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequestBody Body;
        
        public GenerarConsumoRequest() {
        }
        
        public GenerarConsumoRequest(CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarConsumoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceReferenceValeConsumo.ValeConsumo valeConsumo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CapaGUI.ServiceReferenceValeConsumo.Salida[] salidas;
        
        public GenerarConsumoRequestBody() {
        }
        
        public GenerarConsumoRequestBody(CapaGUI.ServiceReferenceValeConsumo.ValeConsumo valeConsumo, CapaGUI.ServiceReferenceValeConsumo.Salida[] salidas) {
            this.valeConsumo = valeConsumo;
            this.salidas = salidas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarConsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarConsumoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponseBody Body;
        
        public GenerarConsumoResponse() {
        }
        
        public GenerarConsumoResponse(CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerarConsumoResponseBody {
        
        public GenerarConsumoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceValeConsumoSoapChannel : CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceValeConsumoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap>, CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap {
        
        public WebServiceValeConsumoSoapClient() {
        }
        
        public WebServiceValeConsumoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceValeConsumoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceValeConsumoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceValeConsumoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponse CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap.HelloWorld(CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest inValue = new CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest();
            inValue.Body = new CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequestBody();
            CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponse retVal = ((CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponse> CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap.HelloWorldAsync(CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceReferenceValeConsumo.HelloWorldResponse> HelloWorldAsync() {
            CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest inValue = new CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequest();
            inValue.Body = new CapaGUI.ServiceReferenceValeConsumo.HelloWorldRequestBody();
            return ((CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponse CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap.GenerarConsumo(CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest request) {
            return base.Channel.GenerarConsumo(request);
        }
        
        public void GenerarConsumo(CapaGUI.ServiceReferenceValeConsumo.ValeConsumo valeConsumo, CapaGUI.ServiceReferenceValeConsumo.Salida[] salidas) {
            CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest inValue = new CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest();
            inValue.Body = new CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequestBody();
            inValue.Body.valeConsumo = valeConsumo;
            inValue.Body.salidas = salidas;
            CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponse retVal = ((CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap)(this)).GenerarConsumo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponse> CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap.GenerarConsumoAsync(CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest request) {
            return base.Channel.GenerarConsumoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoResponse> GenerarConsumoAsync(CapaGUI.ServiceReferenceValeConsumo.ValeConsumo valeConsumo, CapaGUI.ServiceReferenceValeConsumo.Salida[] salidas) {
            CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest inValue = new CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequest();
            inValue.Body = new CapaGUI.ServiceReferenceValeConsumo.GenerarConsumoRequestBody();
            inValue.Body.valeConsumo = valeConsumo;
            inValue.Body.salidas = salidas;
            return ((CapaGUI.ServiceReferenceValeConsumo.WebServiceValeConsumoSoap)(this)).GenerarConsumoAsync(inValue);
        }
    }
}
